deploy feature:
  stage: deploy
  image:
    name: faucherb94/heroku-deployer
    entrypoint: ["/bin/sh", "-c"]
  script:
    - ./heroku_create_feature.sh
    - heroku config:set -a cbapi-$CI_ENVIRONMENT_SLUG DB_ROOT=$DB_ROOT CB_PASS=$CB_PASS > /dev/null
    - git push -u https://heroku:$HEROKU_API_KEY@git.heroku.com/cbapi-$CI_ENVIRONMENT_SLUG.git HEAD:master
  environment:
    name: feature/$CI_COMMIT_REF_NAME
    url: https://cbapi-$CI_ENVIRONMENT_SLUG.herokuapp.com/
  only:
    - branches
  except:
    - master

deploy staging:
  stage: deploy
  image:
    name: faucherb94/heroku-deployer
    entrypoint: ["/bin/sh", "-c"]
  script:
    - heroku config:set -a cbapi-staging DB_ROOT=$DB_ROOT CB_PASS=$CB_PASS > /dev/null
    - git push -u https://heroku:$HEROKU_API_KEY@git.heroku.com/cbapi-staging.git HEAD:master
  environment:
    name: staging
    url: https://cbapi-staging.herokuapp.com/
  only:
    - master
