stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt

deploy review:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --api_key=$HEROKU_API_KEY --app=cb-$CI_ENVIRONMENT_SLUG
  environment:
    name: feature/$CI_COMMIT_REF_NAME
    url: https://cb-$CI_ENVIRONMENT_SLUG.heroku.com/
  except:
    - master
