deploy review:
  stage: deploy
  script:
    - git show-ref
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku create cbapi-$CI_ENVIRONMENT_SLUG
    - heroku config:set DB_ROOT=$DB_ROOT CB_PASS=$CB_PASS > /dev/null
    - git push heroku $CI_COMMIT_REF_NAME:master
  environment:
    name: feature/$CI_COMMIT_REF_NAME
    url: https://cbapi-$CI_ENVIRONMENT_SLUG.heroku.com/
  except:
    - master
