pipelines:
  default:
    - step:
        name: deploy-feature
        image: faucherb94/heroku-deployer
        deployment: test
        script:
          - ./bb_heroku_create_feature.sh
          - heroku config:set -a cbapi-$BITBUCKET_BRANCH DB_ROOT=$DB_ROOT CB_PASS=$CB_PASS > /dev/null
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/cbapi-$BITBUCKET_BRANCH.git HEAD:master
  branches:
    master:
      - step:
          name: deploy-staging
          image: faucherb94/heroku-deployer
          deployment: staging
